// Code de jeu indépendant du moteur. Ne dépend que de l'API libGDX, jamais d'un backend.

dependencies {
    api "com.badlogicgames.gdx:gdx:$gdxVersion"

    testImplementation platform("org.junit:junit-bom:$junitVersion")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
